### ISSUE TITLE
Is Embeddings.search() support model that is not trained to support bi-encoder method? 

### ISSUE THREAD

**Issue by muazhari** [neuml/txtai#320] opened 2022-08-13 12:17 UTC
Based on what I know, how the Embeddings underlying feature works is the same as the bi-encoder method. If I am using a model that is not trained to be used in a bi-encoder method like this [bert-multilingual-passage-reranking-msmarco model](https://huggingface.co/amberoad/bert-multilingual-passage-reranking-msmarco), is it still supported and gives significant result? Because when I evaluate that model with the bi-encoder method (I didn't use txtai library at all when evaluating), the evaluation score leads to the interpretation that the model can't be used because it has a near zero NDCG@10 score (scale of 0-1). If the Embeddings feature did not support cross-encoder, is there some feature that supports it or some workaround?

By using bi-encoder method:
![image](https://user-images.githubusercontent.com/39398937/184493843-152031d6-8eac-4ff6-a334-78b59ec206d3.png)

By using cross-encoder method (divide by 100):
![image](https://user-images.githubusercontent.com/39398937/184493405-537e3de1-58f1-418d-998c-2e8685f737e4.png)

**Comment by davidmezzetti** [comment] 2022-08-15 21:40
Embeddings requires a method to vectorize content into an array of numbers. Those vectors are loaded into an approximate nearest neighbor (ANN) index and made searchable. This is done using bi-encoder models as mentioned. 

Cross-encoder models compute similarity directly between pairs of text. `bert-multilingual-passage-reranking-msmarco` appears to be more of a cross-encoder model since it works on pairs of text.

txtai has a [similarity pipeline](https://neuml.github.io/txtai/pipeline/text/similarity/) that works with MNLI models. The referenced model looks to be more of a regression model since it outputs a single value between -10 to 10. The [labels pipeline](https://neuml.github.io/txtai/pipeline/text/labels/) can be used to act as a cross-encoder in this case. Example below. 

```python
from txtai.pipeline import Labels

data = ["US tops 5 million confirmed virus cases",
        "Canada's last fully intact ice shelf has suddenly collapsed, forming a Manhattan-sized iceberg",
        "Beijing mobilises invasion craft along coast as Taiwan tensions escalate",
        "The National Park Service warns against sacrificing slower friends in a bear attack",
        "Maine man wins $1M from $25 lottery ticket",
        "Make huge profits without work, earn up to $100,000 a day"]

labels = Labels("amberoad/bert-multilingual-passage-reranking-msmarco")
labels("wildlife", data)
```

The same can also be accomplished using standard Hugging Face classes (i.e. AutoTokenizer/AutoModel).

As with the similarity pipeline and cross-encoders, this method could be used as a way to re-rank search results. But unfortunately, it can't be used to encode a meaningful embeddings vector.

**Comment by davidmezzetti** [comment] 2022-08-30 13:13
Closing this as completed. If there are further questions please feel free to re-open or open a new issue.

**Closed by davidmezzetti** 2022-08-30 13:13 UTC
