### ISSUE TITLE
Hybrid scores issue?

### ISSUE THREAD

**Issue by Vincent-liuwingsang** [neuml/txtai#543] opened 2023-09-03 12:03 UTC
The default weightings for hybrid scores are computed from half sparse and half dense.

The top X result from sparse and dense don't necessarily match in uid so if a uid exist in sparse but not dense, the score will be halved.

In this case, shouldn't we retrieve the missing dense score and compute the final score that way🤔

**Comment by davidmezzetti** [comment] 2023-09-03 12:48
This is by design based on the underlying convex combination and RRF methods (see #509). I could see it both ways and you could say the same for the other direction (in dense but not sparse). Do you pay a penalty for not being in the top N?

From a performance standpoint, running 3 queries (sparse, dense and another sparse/dense) seems like it would be quite slow. Perhaps you can accomplish what you're looking to do with a large enough limit, to prevent the additional query.

**Comment by Vincent-liuwingsang** [comment] 2023-09-03 12:59
makes sense I only realised the issue as my dataset has loads of duplicate texts and noticed the same texts have different scores.

Happy to close.

**Comment by davidmezzetti** [comment] 2023-09-22 16:56
Closing this as there doesn't appear to be any actions.

**Closed by davidmezzetti** 2023-09-22 16:56 UTC
